# Generated by Django 5.1.2 on 2024-10-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_method',
            field=models.CharField(max_length=10),
        ),
    ]
